##name: Verify Tests Pass
on:
  pull_request:
    branches:
      - main
      - dev
      # TODO(look): remove these (after verifying)
      - add-expression-tests
  push:
    branches:
      - main
      - dev
      - add-expression-tests
jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Cache maven dependencies across job runs, to speed things up:
      # https://docs.github.com/en/actions/how-tos/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven#caching-dependencies
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Verify Tests Pass
        run: mvn --batch-mode --update-snapshots verify
